/**
 * Generates `src/joins.ts`, the closed-compound rejoin lexicon the search applies after
 * `decompose` on both the index and the query.
 *
 * `compoundLexicon` canonicalises open-preferred compounds onto their open spelling; this is its
 * mirror. A compound the corpus prefers written whole — `snowball`, `homework`, `bedtime` — is
 * one rare token in the index, but a reader may type it open (`snow ball`) and find nothing,
 * because neither half reaches the other. Joining two neighbouring terms back onto the closed
 * form makes `snow ball` and `snowball` one thing, exactly as `goodnight` and `good night`
 * already are.
 *
 * The rule is the inverse of `compoundLexicon` and inherits its safety: only compounds the
 * corpus prefers closed are joined, so a word is either split by `COMPOUNDS` or joined by this
 * map, never both, and ties go to splitting. The bigrams that would wreck a general join —
 * `in to`, `may be`, `a way` — are open-preferred and therefore already split; they never reach
 * this rule. The rest of the frequent two-word phrases are one- and two-letter words, excluded
 * by `MINIMUM_PART`.
 *
 * This is still a candidate list, not the final answer: a closed word whose two halves happen
 * to be words (`carpet` from `car` + `pet`) is proposed even though it is no compound, and the
 * reader of the generated file is expected to prune it. Run with `yarn joins`, then prune.
 */
import fs from "fs";
import path from "path";
import { loadComicSource } from "./comicSource";
import { stem } from "../src/stem";

const WORD_PATTERN = /[\p{L}\p{N}']+/gu;

// Both halves must be real words of their own, and long enough not to be an artefact: a
// two-letter fragment matches far too much to be worth joining.
const MINIMUM_PART = 3;

interface Counts {
	words: Map<string, number>;
	bigrams: Map<string, number>;
}

function tokenise(text: string): string[] {
	return [...text.matchAll(WORD_PATTERN)].map((match) => match[0].toLowerCase());
}

// Sound effects and elongations (`aaaa`, `brr`, `hmm`, `zzz`) repeat a couple of letters and
// would otherwise propose `aaa` -> `aaabbb` and the like. A word needs three distinct letters
// to be a word worth joining.
function distinctLetters(word: string): number {
	return new Set(word).size;
}

// Document frequency, not term frequency: one strip counts once however often it repeats a
// word, matching how `countDocument` builds the corpus the scorer reads.
function count(documents: string[][]): Counts {
	const words = new Map<string, number>();
	const bigrams = new Map<string, number>();

	for (const tokens of documents) {
		const seenWords = new Set<string>();
		const seenBigrams = new Set<string>();
		for (let index = 0; index < tokens.length; index++) {
			seenWords.add(tokens[index]);
			if (index + 1 < tokens.length) seenBigrams.add(`${tokens[index]} ${tokens[index + 1]}`);
		}
		for (const word of seenWords) words.set(word, (words.get(word) || 0) + 1);
		for (const bigram of seenBigrams) bigrams.set(bigram, (bigrams.get(bigram) || 0) + 1);
	}

	return { words, bigrams };
}

export function buildLexicon(projectDir: string): Map<string, string> {
	const source = loadComicSource(path.join(projectDir, "comics.yaml"));

	// A strip is one document across all of its text. Descriptions share `indexField` with
	// transcripts, so they have to inform the lexicon that will be applied to them.
	const documents: string[][] = [];
	for (const entry of [...Object.values(source.dailies), ...Object.values(source.specials)]) {
		documents.push(tokenise([entry.transcript, entry.alternate || "", entry.description || ""].join(" ")));
	}

	const { words, bigrams } = count(documents);
	const joins = new Map<string, string>();

	for (const [closed, closedDf] of words) {
		if (closed.length < MINIMUM_PART * 2) continue;
		if (distinctLetters(closed) <= 2) continue;

		for (let cut = MINIMUM_PART; cut <= closed.length - MINIMUM_PART; cut++) {
			const left = closed.slice(0, cut);
			const right = closed.slice(cut);
			if (!words.has(left) || !words.has(right)) continue;

			// An inflection, not a compound: the closed form shares a stem with one of its
			// halves. The stemmer owns those.
			if (stem(closed) === stem(left) || stem(closed) === stem(right)) continue;

			const openDf = bigrams.get(`${left} ${right}`) || 0;
			// The corpus must prefer the closed spelling. Ties go to `compoundLexicon`, whose
			// split already rewrites both spellings onto the open form; joining here too would
			// fight it.
			if (openDf >= closedDf) continue;

			joins.set(`${left} ${right}`, closed);
			break;
		}
	}

	return new Map([...joins].sort(([a], [b]) => a.localeCompare(b)));
}

function render(joins: Map<string, string>): string {
	const entries = [...joins].map(([open, closed]) => `\t["${open}", "${closed}"],`).join("\n");

	// Emitted tab-indented and double-quoted to match the prettier config, so the generated
	// file is already formatted.
	return `// Generated by build-chain/joinLexicon.ts — run \`yarn joins\`. Do not edit by hand.
//
// Open bigrams whose closed form this corpus prefers, joined back after \`decompose\` on both
// the index and the query, so \`snow ball\` and \`snowball\` are one thing. The inverse of
// \`COMPOUNDS\`: a word is split by that map or joined by this one, never both.

export const JOINS: Map<string, string> = new Map([
${entries}
]);
`;
}

const projectDir = process.cwd();
const joins = buildLexicon(projectDir);
const target = path.join(projectDir, "src", "joins.ts");
fs.writeFileSync(target, render(joins));
console.log(`wrote ${joins.size} joins to ${path.relative(projectDir, target)}`);
for (const [open, closed] of joins) console.log(`  ${open} -> ${closed}`);
