// Generated by build-chain/compoundLexicon.ts — run `yarn compounds`. Do not edit by hand.
//
// Compounds are rewritten onto their parts for matching. Required entries cover relationships
// that the corpus does not expose often enough for statistical discovery.

export const COMPOUNDS: Map<string, string[]> = new Map([
	["allright", ["all", "right"]],
	["anymore", ["any", "more"]],
	["anytime", ["any", "time"]],
	["babysitter", ["baby", "sitter"]],
	["backyard", ["back", "yard"]],
	["boogerbrain", ["booger", "brain"]],
	["comeback", ["come", "back"]],
	["flamethrower", ["flame", "thrower"]],
	["flyswatter", ["fly", "swatter"]],
	["fuzzbrain", ["fuzz", "brain"]],
	["getaway", ["get", "away"]],
	["goodnight", ["good", "night"]],
	["grownups", ["grown", "ups"]],
	["hotdog", ["hot", "dog"]],
	["hotdogs", ["hot", "dogs"]],
	["letdown", ["let", "down"]],
	["lookout", ["look", "out"]],
	["lunchbox", ["lunch", "box"]],
	["rocketship", ["rocket", "ship"]],
	["runaway", ["run", "away"]],
	["schoolbooks", ["school", "books"]],
	["snowball", ["snow", "ball"]],
	["stepladder", ["step", "ladder"]],
	["superpowers", ["super", "powers"]],
	["takeoff", ["take", "off"]],
	["teenager", ["teen", "ager"]],
	["thermonuclear", ["thermo", "nuclear"]],
	["turnaround", ["turn", "around"]],
	["workout", ["work", "out"]],
]);
