// Generated by build-chain/compoundLexicon.ts — run `yarn compounds`. Do not edit by hand.
//
// Relations preserve whole-form identity; canonical forms are a derived matching/indexing view.
// Required entries cover relationships that the corpus does not expose often enough for discovery.

export interface CompoundRelation {
	whole: string;
	parts: string[];
	preference: "open" | "closed" | "balanced";
}

export const COMPOUND_RELATIONS: Map<string, CompoundRelation> = new Map([
	["allright", { whole: "allright", parts: ["all", "right"], preference: "open" }],
	["anymore", { whole: "anymore", parts: ["any", "more"], preference: "open" }],
	["anytime", { whole: "anytime", parts: ["any", "time"], preference: "open" }],
	["babysitter", { whole: "babysitter", parts: ["baby", "sitter"], preference: "open" }],
	["backyard", { whole: "backyard", parts: ["back", "yard"], preference: "open" }],
	["boogerbrain", { whole: "boogerbrain", parts: ["booger", "brain"], preference: "open" }],
	["comeback", { whole: "comeback", parts: ["come", "back"], preference: "open" }],
	["flamethrower", { whole: "flamethrower", parts: ["flame", "thrower"], preference: "open" }],
	["flyswatter", { whole: "flyswatter", parts: ["fly", "swatter"], preference: "open" }],
	["fuzzbrain", { whole: "fuzzbrain", parts: ["fuzz", "brain"], preference: "open" }],
	["getaway", { whole: "getaway", parts: ["get", "away"], preference: "open" }],
	["goodnight", { whole: "goodnight", parts: ["good", "night"], preference: "open" }],
	["grownups", { whole: "grownups", parts: ["grown", "ups"], preference: "open" }],
	["hotdog", { whole: "hotdog", parts: ["hot", "dog"], preference: "open" }],
	["hotdogs", { whole: "hotdogs", parts: ["hot", "dogs"], preference: "open" }],
	["letdown", { whole: "letdown", parts: ["let", "down"], preference: "open" }],
	["lookout", { whole: "lookout", parts: ["look", "out"], preference: "open" }],
	["lunchbox", { whole: "lunchbox", parts: ["lunch", "box"], preference: "open" }],
	["rocketship", { whole: "rocketship", parts: ["rocket", "ship"], preference: "open" }],
	["runaway", { whole: "runaway", parts: ["run", "away"], preference: "open" }],
	["schoolbooks", { whole: "schoolbooks", parts: ["school", "books"], preference: "open" }],
	["snowball", { whole: "snowball", parts: ["snow", "ball"], preference: "balanced" }],
	["stepladder", { whole: "stepladder", parts: ["step", "ladder"], preference: "open" }],
	["superpowers", { whole: "superpowers", parts: ["super", "powers"], preference: "open" }],
	["takeoff", { whole: "takeoff", parts: ["take", "off"], preference: "open" }],
	["teenager", { whole: "teenager", parts: ["teen", "ager"], preference: "open" }],
	["thermonuclear", { whole: "thermonuclear", parts: ["thermo", "nuclear"], preference: "open" }],
	["turnaround", { whole: "turnaround", parts: ["turn", "around"], preference: "open" }],
	["workout", { whole: "workout", parts: ["work", "out"], preference: "open" }],
]);

export const COMPOUND_CANONICAL_FORMS: Map<string, string[]> = new Map(
	[...COMPOUND_RELATIONS].map(([whole, relation]) => [whole, relation.parts]),
);
