// Generated by build-chain/compoundLexicon.ts — run `yarn compounds`. Do not edit by hand.
//
// Closed compounds this corpus writes more often in the open form. The index and the query
// are both rewritten onto the open spelling, so `goodnight` and `good night` are one thing.
// Compounds the corpus prefers closed — `snowman`, `homework`, `bedtime` — are absent by
// design: they are the rare tokens doing the admitting, and splitting them spends that rarity.

export const COMPOUNDS: Map<string, string[]> = new Map([
	["anymore", ["any", "more"]],
	["anytime", ["any", "time"]],
	["babysitter", ["baby", "sitter"]],
	["backyard", ["back", "yard"]],
	["boogerbrain", ["booger", "brain"]],
	["comeback", ["come", "back"]],
	["flamethrower", ["flame", "thrower"]],
	["flyswatter", ["fly", "swatter"]],
	["fuzzbrain", ["fuzz", "brain"]],
	["getaway", ["get", "away"]],
	["goodnight", ["good", "night"]],
	["grownups", ["grown", "ups"]],
	["hotdog", ["hot", "dog"]],
	["hotdogs", ["hot", "dogs"]],
	["lookout", ["look", "out"]],
	["lunchbox", ["lunch", "box"]],
	["lunchtime", ["lunch", "time"]],
	["runaway", ["run", "away"]],
	["schoolbooks", ["school", "books"]],
	["stepladder", ["step", "ladder"]],
	["superhighway", ["super", "highway"]],
	["superpowers", ["super", "powers"]],
	["takeoff", ["take", "off"]],
	["teenager", ["teen", "ager"]],
	["thermonuclear", ["thermo", "nuclear"]],
	["turnaround", ["turn", "around"]],
	["workout", ["work", "out"]],
]);
