// Seeded by build-chain/derivationLexicon.ts — run `yarn derivations`, then prune by hand.
// Regenerating replaces this file with the full candidate set, so prune only after regenerating.
//
// The base words and the closed compounds they may legitimately reach. Only the pairs listed
// here bridge: `snow` reaches `snowball`, and `car` never reaches `carrot` because no
// entry says so. The general string-prefix rule this replaced is off by default. Inflections
// are the stemmer's job and stay out of this list.

export const DERIVATIONS: Map<string, string[]> = new Map([
	["aarg", ["aargghh"]],
	["accept", ["acceptable"]],
	["account", ["accountability"]],
	["adult", ["adulthood"]],
	["after", ["afterlife", "afternoon"]],
	["air", ["aircraft", "airline", "airplane", "airplanes", "airport", "airports", "airtight"]],
	["alley", ["alleyway"]],
	["anima", ["animated"]],
	["ant", ["anteater"]],
	["anti", ["antibodies", "antiseptic", "antisocial"]],
	["any", ["anybody", "anybody's", "anyone", "anyone's", "anything", "anyway", "anywhere"]],
	["apple", ["applesauce"]],
	["arm", ["armpit"]],
	["art", ["artwork"]],
	["ash", ["ashtray"]],
	["attract", ["attractive"]],
	["avail", ["available"]],
	["aware", ["awareness"]],
	["back", ["background", "backpack"]],
	["bad", ["badlands", "badness"]],
	["band", ["bandage", "bandages"]],
	["bar", ["bargain", "bargin", "barking", "barrage"]],
	["base", ["baseball", "baseman", "basepath"]],
	["basket", ["basketball"]],
	["bat", ["batman"]],
	["bath", ["bathroom", "bathtub"]],
	["battle", ["battleship"]],
	["beach", ["beachball"]],
	["beat", ["beating"]],
	["bed", ["bedbug", "bedbugs", "bedroom", "bedsheet", "bedspread", "bedtime", "bedtimes"]],
	["beg", ["beginning", "begins"]],
	["belly", ["bellylander"]],
	["bet", ["betrays"]],
	["bill", ["billboard"]],
	["bin", ["binder", "binding"]],
	["birth", ["birthday"]],
	["bit", ["biting"]],
	["black", ["blackboard", "blackmail", "blackness"]],
	["blame", ["blameless"]],
	["bland", ["blandness"]],
	["blast", ["blasters"]],
	["blind", ["blindfold"]],
	["bliss", ["blissfully"]],
	["blood", ["bloodsucking", "bloodthirsty"]],
	["blow", ["blowhard"]],
	["bluff", ["bluffing"]],
	["board", ["boardwalk"]],
	["bomb", ["bombers"]],
	["bone", ["bonehead"]],
	["book", ["bookcase"]],
	["bot", ["bother", "bothers", "bottom"]],
	["bow", ["bowled"]],
	["boy", ["boyfriend", "boyfriends"]],
	["brain", ["brainless", "brainstorms", "brainwash", "brainwashed"]],
	["bran", ["branding"]],
	["break", ["breakers", "breakfast", "breakneck", "breakthing"]],
	["breath", ["breathable"]],
	["brief", ["briefcase"]],
	["bro", ["brother"]],
	["broad", ["broadcast"]],
	["broom", ["broomstick"]],
	["buck", ["buckeye"]],
	["bud", ["buddies", "budget"]],
	["bullet", ["bulletins"]],
	["bum", ["bumper"]],
	["bun", ["bungee"]],
	["bur", ["burper", "burping"]],
	["bus", ["busload"]],
	["bust", ["busters"]],
	["busy", ["busywork"]],
	["but", ["button", "buttons"]],
	["butter", ["butterfly"]],
	["buy", ["buyers"]],
	["cal", ["called"]],
	["calvin", ["calvinball"]],
	["camp", ["campers", "campfire", "campground", "campsite"]],
	["can", ["candance", "candid", "cannon", "cannot"]],
	["cannibal", ["cannibalism"]],
	["cannon", ["cannonball"]],
	["car", ["caring", "carpet", "carroll", "carrot", "carton"]],
	["card", ["cardboard"]],
	["care", ["careful", "carefully", "careless"]],
	["cat", ["caters"]],
	["cave", ["caveman"]],
	["cent", ["centers"]],
	["certain", ["certainties"]],
	["chain", ["chainsaw", "chainsaws"]],
	["chalk", ["chalkboard"]],
	["champion", ["championship"]],
	["chas", ["chasing"]],
	["cheap", ["cheapskate"]],
	["cheat", ["cheating"]],
	["check", ["checkers"]],
	["cheer", ["cheerful", "cheerfully", "cheerleaders"]],
	["chew", ["chewers"]],
	["child", ["childhood"]],
	["choo", ["chooses", "choosing"]],
	["chowder", ["chowderhead", "chowderheads"]],
	["christmas", ["christmassss"]],
	["class", ["classmate", "classroom"]],
	["clean", ["cleaners"]],
	["climb", ["climbers"]],
	["clip", ["clipper"]],
	["club", ["clubhouse"]],
	["collaps", ["collapsing"]],
	["color", ["colorless"]],
	[
		"com",
		[
			"combat",
			"combed",
			"combing",
			"combust",
			"comfort",
			"coming",
			"commission",
			"commotion",
			"compass",
			"compete",
			"compiling",
			"complain",
			"compose",
			"compost",
			"compound",
			"compromise",
		],
	],
	["comb", ["combine"]],
	["combat", ["combatant"]],
	["comfort", ["comfortable"]],
	["commercial", ["commercialism"]],
	["commit", ["committee"]],
	["companion", ["companionship"]],
	[
		"con",
		[
			"concord",
			"concur",
			"conduct",
			"confine",
			"confirm",
			"conform",
			"confound",
			"confounded",
			"confuse",
			"confused",
			"conscience",
			"contemporary",
			"content",
			"contents",
			"contest",
			"contests",
			"context",
			"contract",
			"contractor",
			"conversion",
			"conversions",
		],
	],
	["conscious", ["consciousness"]],
	["consumer", ["consumerism"]],
	["control", ["controlled"]],
	["cook", ["cookout"]],
	["cop", ["coping"]],
	["copy", ["copyright"]],
	["corn", ["corners"]],
	["count", ["countdown", "counters", "countless"]],
	["cow", ["cowboy"]],
	["crack", ["crackers", "crackpot"]],
	["cram", ["cramping"]],
	["cross", ["crossbones", "crossword"]],
	["crystal", ["crystalline"]],
	["cur", ["curled", "current", "curses"]],
	["curl", ["curlers"]],
	["cut", ["cutthroat"]],
	["dam", ["damage", "damages"]],
	["dang", ["dangers"]],
	["dark", ["darkness"]],
	["day", ["daylight"]],
	["dead", ["deadline", "deadlines", "deadman's"]],
	["death", ["deathbed"]],
	["defect", ["defective"]],
	["defend", ["defendant"]],
	["defense", ["defenseless"]],
	["delight", ["delightful"]],
	["dep", ["depend", "depended", "depends"]],
	["detect", ["detective"]],
	["devil", ["devilled"]],
	["dig", ["digits"]],
	["din", ["dining"]],
	["discus", ["discussing"]],
	["disgust", ["disgustink"]],
	["dog", ["doggone"]],
	["don", ["donate"]],
	["door", ["doorbell", "doormat", "doorway"]],
	["down", ["downhill", "downpour", "downshifts", "downslope", "downstairs", "downtown"]],
	["dragon", ["dragonflies"]],
	["drain", ["drainage"]],
	["draw", ["drawers"]],
	["drink", ["drinkers"]],
	["drip", ["drippig"]],
	["drive", ["driveway", "driveways"]],
	["drum", ["drumsticks"]],
	["dum", ["dumbest"]],
	["dumb", ["dumbfounded"]],
	["dweeb", ["dweebism"]],
	["ear", ["earnest"]],
	["earthling", ["earthlingburgers"]],
	["eat", ["eating"]],
	["effect", ["effective"]],
	["effort", ["effortless"]],
	["eleven", ["eleventeen"]],
	["else", ["elsewhere"]],
	["end", ["endangered", "endless"]],
	["ever", ["everbody", "everthing"]],
	["every", ["everybody", "everybody's", "everyone", "everyone's", "everything", "everywhere"]],
	["exam", ["examine"]],
	["excess", ["excessive"]],
	["fan", ["fanged"]],
	["far", ["farther"]],
	["fat", ["father", "fathom"]],
	["father", ["fatherhood"]],
	["fear", ["fearless", "fearsome", "fearson"]],
	["feather", ["featherbrained"]],
	["fiend", ["fiendish"]],
	["fight", ["fighters"]],
	["figure", ["figurehead"]],
	["find", ["finders"]],
	["finger", ["fingernails"]],
	[
		"fire",
		["firearms", "fireball", "fireflies", "firefly", "fireman", "firemen", "fireplace", "firepower", "fireworks"],
	],
	["fit", ["fitness"]],
	["flag", ["flagstaff"]],
	["flash", ["flashlight"]],
	["flat", ["flatfoot"]],
	["flea", ["fleabag"]],
	["flip", ["flippant"]],
	["float", ["floating"]],
	["flood", ["floodlights"]],
	["floor", ["floorboards"]],
	["fool", ["foolish"]],
	["foot", ["football", "footnote", "footprints", "footstep", "footsteps"]],
	[
		"for",
		[
			"forage",
			"forbidding",
			"forever",
			"forget",
			"forgets",
			"forgetting",
			"forgive",
			"forgot",
			"forgotten",
			"fortunes",
		],
	],
	["fore", ["forearm", "foregone", "forehead", "foresight"]],
	["fork", ["forklift"]],
	["forth", ["forthwith"]],
	["four", ["fourteen"]],
	["free", ["freezing"]],
	["friend", ["friendship", "friendships"]],
	["fro", ["frosting", "frozen"]],
	["frost", ["frostbite"]],
	["ful", ["fulfill", "fulfilling", "fulfills"]],
	["fun", ["funding"]],
	["fur", ["furball", "further"]],
	["fuzz", ["fuzzhead"]],
	["gang", ["gangway"]],
	["gas", ["gasping"]],
	["geez", ["geezers"]],
	["gene", ["generally", "generate", "generations"]],
	["gentle", ["gentleman", "gentleman's", "gentlemen"]],
	["girl", ["girlfriend"]],
	["god", ["godless"]],
	["good", ["goodbye", "goodness"]],
	["goose", ["goosebumps"]],
	["got", ["gotten"]],
	["govern", ["governess", "governmental"]],
	["grace", ["gracefully"]],
	["grand", ["grandfather", "grandfather's", "grandmother"]],
	["great", ["greatness"]],
	["green", ["greenbacks", "greenhouse", "greenish"]],
	["grin", ["grinding"]],
	["grip", ["griping"]],
	["gross", ["grossness"]],
	["ground", ["groundhog"]],
	["gues", ["guesses", "guessing", "guessss"]],
	["guide", ["guidelines"]],
	["hack", ["hacksaw"]],
	["hair", ["hairball", "haircut", "hairless"]],
	["half", ["halfback", "halfway"]],
	["hall", ["hallway"]],
	["ham", ["hamburger", "hamburgers", "hamlet's"]],
	["hand", ["handguns", "handshake", "handsome", "handwriting"]],
	["handle", ["handlebar", "handlebars"]],
	["hap", ["happen", "happier"]],
	["har", ["harder"]],
	["hard", ["hardback", "hardcover"]],
	["harm", ["harmless"]],
	["hat", ["hatred"]],
	["head", ["headless", "headlights", "headlines"]],
	["heal", ["healthy"]],
	["heart", ["heartache", "heartfelt", "heartless", "heartstrings"]],
	["heat", ["heating"]],
	["help", ["helpless"]],
	["her", ["herself"]],
	["hero", ["heroine"]],
	["hic", ["hiccup", "hiccups"]],
	["hid", ["hiding"]],
	["hideous", ["hideousness"]],
	["high", ["highway"]],
	["hill", ["hillside"]],
	["him", ["himself"]],
	["his", ["hisses"]],
	["home", ["homemade", "homework"]],
	["honey", ["honeymoon"]],
	["hop", ["hoping"]],
	["hope", ["hopeless"]],
	["horizon", ["horizontally"]],
	["hors", ["horsing"]],
	["horse", ["horsefly", "horseman"]],
	["host", ["hostage", "hostages", "hostile"]],
	["hot", ["hottest", "hotwire"]],
	["house", ["housefly", "household", "housekeeping"]],
	["how", ["however"]],
	["hum", ["humself"]],
	["humble", ["humbleness"]],
	["humming", ["hummingbird"]],
	["hung", ["hungers"]],
	["hyper", ["hyperbubble", "hyperspace"]],
	["ice", ["icebox"]],
	["idea", ["idealists"]],
	["imagin", ["imaginable"]],
	["impress", ["impressive"]],
	["impression", ["impressionable"]],
	["inch", ["inchworm"]],
	["inhabit", ["inhabitants"]],
	["inter", ["interact", "interaction", "interbeing", "interdimensional", "interpersonal", "interview"]],
	["interact", ["interactive"]],
	["invent", ["inventive"]],
	["it's", ["it'ssss"]],
	["its", ["itself"]],
	["jack", ["jackpot"]],
	["jaw", ["jawbone"]],
	["just", ["justice"]],
	["kick", ["kickoffs", "kickstand"]],
	["kid", ["kiddie"]],
	["kind", ["kindness"]],
	["knee", ["kneepads"]],
	["know", ["knowable", "knowledge", "knowwedge"]],
	["lad", ["ladder"]],
	["lake", ["lakeside"]],
	["land", ["landslide"]],
	["lands", ["landscape"]],
	["law", ["lawyer"]],
	["lay", ["layers", "layman"]],
	["lead", ["leaders"]],
	["leader", ["leadership"]],
	["left", ["leftover"]],
	["leg", ["leglock"]],
	["letter", ["letterhead"]],
	["life", ["lifeguard", "lifeless", "lifetime"]],
	["light", ["lightweight"]],
	["like", ["likeable", "likeness"]],
	["lip", ["lipstick"]],
	["lite", ["literate"]],
	["live", ["livestock"]],
	["lock", ["lockjaw"]],
	["loop", ["loophole", "loopholes"]],
	["low", ["lowbrow"]],
	["lunch", ["lunchroom", "lunchtime"]],
	["mail", ["mailbox", "mailman"]],
	["main", ["mainstream"]],
	["man", ["manage", "manager", "mandate", "mankind"]],
	["manage", ["manageable"]],
	["maneuver", ["maneuverability", "maneuverable"]],
	["market", ["marketability", "marketable"]],
	["mass", ["massacre", "massive"]],
	["mast", ["masters"]],
	["master", ["mastercard", "mastermind", "masterpiece", "masterpieces"]],
	["mat", ["mating"]],
	["match", ["matchmaker"]],
	["may", ["mayday"]],
	["mean", ["meantime", "meanwhile"]],
	["meaning", ["meaningful", "meaningless"]],
	["meat", ["meatloaf"]],
	["member", ["membership"]],
	["men", ["menace"]],
	["mess", ["message", "messages"]],
	["mid", ["midnight"]],
	["mile", ["mileage"]],
	["mind", ["mindless"]],
	["mini", ["minimum"]],
	["miss", ["missile"]],
	["mist", ["mistreat"]],
	["mocking", ["mockingbird"]],
	["moon", ["moonlight", "moonlit"]],
	["mop", ["moping"]],
	["moth", ["mothers"]],
	["motion", ["motionless"]],
	["mouth", ["mouthpiece"]],
	["muck", ["muckballs"]],
	["mud", ["muders"]],
	["must", ["mustache", "mustaches", "mustive"]],
	["nation", ["nationwide"]],
	["neck", ["necktie"]],
	["need", ["needless"]],
	["net", ["network", "networks"]],
	["news", ["newspaper", "newspapers", "newsworthy"]],
	["night", ["nighttime"]],
	["noodle", ["noodleloaf"]],
	["north", ["northeast"]],
	["not", ["notice", "noticed"]],
	["note", ["notebook", "notebook's", "notebooks", "notepad"]],
	["nothing", ["nothingness"]],
	["now", ["nowhere", "nowmen"]],
	["nuk", ["nuking"]],
	["numb", ["numbers", "numbskull"]],
	["object", ["objective"]],
	["ome", ["omelet"]],
	["one", ["oneself"]],
	["onto", ["ontological"]],
	["other", ["otherwise"]],
	["our", ["ourselves"]],
	[
		"out",
		[
			"outdated",
			"outdoor",
			"outdoors",
			"outfield",
			"outfielder",
			"outfit",
			"outlet",
			"outline",
			"outnumber",
			"outnumbered",
			"output",
			"outrage",
			"outranks",
			"outrun",
			"outside",
			"outstanding",
		],
	],
	["outer", ["outermost"]],
	["outfield", ["outfielders"]],
	[
		"over",
		[
			"overall",
			"overboard",
			"overcharged",
			"overcoat",
			"overcome",
			"overcoming",
			"overflowing",
			"overhaul",
			"overhead",
			"overheard",
			"overlay",
			"overlays",
			"overload",
			"overlooked",
			"overlooking",
			"overnight",
			"overpaid",
			"overpopulation",
			"override",
			"overrun",
			"overseas",
			"oversized",
			"overslept",
			"overview",
		],
	],
	["pack", ["package", "packages"]],
	["pain", ["painless", "painted"]],
	["pan", ["panache", "pancake", "pander", "pantry"]],
	["paper", ["paperwork"]],
	["par", ["pardon", "pardons", "parking", "parted", "parties"]],
	["pass", ["passage", "passive", "password"]],
	["passage", ["passageway"]],
	["passion", ["passionate"]],
	["pay", ["paycheck", "payload"]],
	["pea", ["peanut", "peanuts"]],
	["peace", ["peaceful", "peacefully"]],
	["pen", ["pending"]],
	["penal", ["penalties"]],
	["per", ["perchance", "perform", "performed", "permission", "person"]],
	["photo", ["photograph", "photographic", "photographs"]],
	["pig", ["pigskin"]],
	["pin", ["pinpoint"]],
	["pinch", ["pinchers"]],
	["pine", ["pineapple"]],
	["play", ["playboy", "players", "playground"]],
	["plea", ["pleases", "pleasure"]],
	["pleas", ["pleasant"]],
	["point", ["pointless"]],
	["police", ["policeman"]],
	["pond", ["ponders"]],
	["post", ["postage", "posters", "postmark"]],
	["pow", ["powder", "powers"]],
	["power", ["powerful"]],
	["pray", ["prayers"]],
	["pre", ["predestined", "predetermined", "prehistoric", "premature", "present", "preserve"]],
	["price", ["priceless"]],
	["priori", ["priorities"]],
	["prison", ["prisoners"]],
	[
		"pro",
		[
			"process",
			"proclaiming",
			"proclaims",
			"product",
			"profit",
			"profits",
			"profound",
			"promotion",
			"promotions",
			"pronoun",
			"proper",
			"propose",
			"proposes",
			"proposition",
			"protest",
			"protests",
		],
	],
	["product", ["productive"]],
	["profit", ["profitable"]],
	["proper", ["properties"]],
	["psycho", ["psychological", "psychopath", "psychosomatic"]],
	["publish", ["publishers"]],
	["puff", ["puffing"]],
	["pum", ["pumping"]],
	["pure", ["pureness"]],
	["put", ["putrid", "putties"]],
	["quarter", ["quarterback"]],
	["quick", ["quicksand"]],
	["rail", ["railroad"]],
	["rain", ["rainbows", "raincoat"]],
	["ramp", ["rampage"]],
	["rat", ["rather", "rating"]],
	["reason", ["reasonable"]],
	["rec", ["recall", "recant", "recess", "recorder"]],
	["recess", ["recessive"]],
	["red", ["redheads"]],
	["remark", ["remarkable"]],
	["repeat", ["repeating"]],
	["report", ["reporters"]],
	["respect", ["respectful"]],
	["rest", ["restful", "restore", "restrain"]],
	["retract", ["retractable"]],
	["retro", ["retroactively"]],
	["rid", ["riddance", "riders", "riding"]],
	["right", ["rightful", "rightness", "rightside"]],
	["road", ["roadkill", "roadrunner"]],
	["robin", ["robinson"]],
	["rockets", ["rocketship"]],
	["room", ["roommate"]],
	["rot", ["rotate", "rotten"]],
	["round", ["roundness"]],
	["rude", ["rudeness"]],
	["rug", ["rugget"]],
	["run", ["runway", "runways"]],
	["sail", ["sailboat"]],
	["sand", ["sandbox", "sandman"]],
	["sap", ["sapsucker"]],
	["satan", ["satanism"]],
	["school", ["schoolwork"]],
	["scoot", ["scooters"]],
	["scout", ["scoutmaster"]],
	["scram", ["scrambled"]],
	["screw", ["screwdriver"]],
	["sea", ["seafood", "sealed", "searing", "searow", "season", "seaweed"]],
	["seam", ["seamstress"]],
	["seat", ["seaters"]],
	["secret", ["secretive"]],
	["select", ["selective"]],
	["self", ["selfish"]],
	["set", ["setbacks"]],
	["sew", ["sewage"]],
	["shame", ["shameless"]],
	["sharp", ["sharpshooting"]],
	["shift", ["shifters"]],
	["short", ["shortsighted", "shortstop"]],
	["should", ["shoulders"]],
	["shove", ["shoveled"]],
	["show", ["showers"]],
	["side", ["sidewalk", "sidewalks", "sideways"]],
	["sigh", ["sighted"]],
	["sin", ["sinful", "singed", "sinking", "sinuses"]],
	["since", ["sincerely"]],
	["sit", ["sitcom"]],
	["skate", ["skateboard"]],
	["sleep", ["sleepers", "sleepwalking"]],
	["sleepy", ["sleepyhead"]],
	["slid", ["sliding"]],
	["slush", ["slushball", "slushballs"]],
	["smack", ["smackers"]],
	["smarty", ["smartypants"]],
	["sneak", ["sneakers"]],
	["snow", ["snowball", "snowballs", "snowman", "snowman's", "snowmen"]],
	["sod", ["sodbuster"]],
	["soft", ["softball"]],
	["soggy", ["soggyshorts"]],
	[
		"some",
		[
			"somebody",
			"somebody's",
			"someday",
			"somehow",
			"someone",
			"someone's",
			"someplace",
			"something",
			"sometime",
			"sometimes",
			"somewhat",
			"somewhere",
		],
	],
	["sore", ["sorehead"]],
	["soul", ["soulless"]],
	["south", ["southeast"]],
	["space", ["spacechip", "spacecraft", "spaceman", "spaceship", "spaceships", "spacesuits"]],
	["span", ["spanish"]],
	["spit", ["spitball"]],
	["spoon", ["spoonful"]],
	["sports", ["sportsman"]],
	["spot", ["spotlights"]],
	["spring", ["springboard"]],
	["stair", ["staircase", "stairway"]],
	["star", ["starboard", "staring", "started"]],
	["start", ["starters", "startled"]],
	["stick", ["stickers"]],
	["still", ["stillness"]],
	["stink", ["stinkers", "stinkhead"]],
	["stop", ["stopwatch"]],
	["street", ["streetwise"]],
	["stress", ["stressful"]],
	["stripey", ["stripeypants"]],
	["stuff", ["stuffing"]],
	[
		"sub",
		[
			"subatomic",
			"subcommittee",
			"subconscious",
			"subdue",
			"sublime",
			"submission",
			"subtitles",
			"subtract",
			"subtraction",
		],
	],
	["suc", ["success", "sucking"]],
	["success", ["successful", "successive"]],
	["sugar", ["sugarless"]],
	["suit", ["suitcase"]],
	["sun", ["sunburned", "sunday", "sunday's", "sundays", "sunglasses", "sunlight", "sunrise", "sunshine"]],
	["super", ["superhero", "superheroes", "superhuman", "superimposed", "supermarket", "supertoad"]],
	["surf", ["surface"]],
	["sweat", ["sweaters", "sweatshirts"]],
	["sweet", ["sweetness"]],
	["swim", ["swimsuit", "swimsuits"]],
	["tail", ["tailhook"]],
	["tape", ["tapeworm"]],
	["taste", ["tasteful", "tasteless"]],
	["tea", ["tearing", "teases", "teasing"]],
	["teach", ["teachers"]],
	["team", ["teamwork"]],
	["ten", ["tendon", "tendons"]],
	["terror", ["terrorism"]],
	["text", ["textbooks"]],
	["than", ["thanking"]],
	["the", ["theirs", "thereat"]],
	["them", ["themselves"]],
	["there", ["therefore"]],
	["thick", ["thickness"]],
	["thin", ["thinking"]],
	["thou", ["thousand"]],
	["thought", ["thoughtful", "thoughtless"]],
	["thre", ["threads"]],
	["through", ["throughout"]],
	["thrust", ["thrusters"]],
	["thunder", ["thunderstorm"]],
	["tim", ["timers", "timing"]],
	["time", ["timeless"]],
	["tip", ["tiptoe", "tiptoes"]],
	["tire", ["tireless"]],
	["together", ["togetherness"]],
	["ton", ["tongues"]],
	["tooth", ["toothbrush", "toothbrushes", "toothless", "toothpaste"]],
	["top", ["topsoil"]],
	["totalitarian", ["totalitarianism"]],
	["touch", ["touchdown"]],
	["trade", ["trademark"]],
	["travel", ["travelled"]],
	["treat", ["treating"]],
	["tree", ["treehouse"]],
	["trench", ["trenchant"]],
	["tri", ["triangle", "tricycle", "triumph"]],
	["triumph", ["triumphant"]],
	["troo", ["trooper"]],
	["tru", ["trusting"]],
	["truck", ["truckload"]],
	["tum", ["tumbled"]],
	["turn", ["turnabout"]],
	["type", ["typewriter"]],
	[
		"under",
		[
			"underfoot",
			"underground",
			"underhand",
			"underhanded",
			"underline",
			"underpaid",
			"underpants",
			"undersea",
			"underserved",
			"underside",
			"undersigned",
			"understand",
			"understanding",
			"understands",
			"understatement",
			"understudy",
			"underwear",
			"underweight",
			"underworld",
			"underwrite",
		],
	],
	["use", ["useful", "useless"]],
	["valid", ["validate"]],
	["vandal", ["vandalism"]],
	["victim", ["victimhood"]],
	["video", ["videorama"]],
	["view", ["viewers", "viewpoint"]],
	["vile", ["vileness"]],
	["wad", ["wading"]],
	["wahhh", ["wahhhaahh"]],
	["wal", ["walking", "wallet", "wallow"]],
	["walk", ["walkway"]],
	["wan", ["wander", "wanted", "wanton"]],
	["war", ["warpath", "warping", "warrant"]],
	["was", ["wasted"]],
	["wash", ["washable"]],
	["washing", ["washington"]],
	["waste", ["wasteful"]],
	["water", ["waterfall", "waterfront", "waterways"]],
	["weat", ["weather"]],
	["week", ["weekdays", "weekend", "weekends"]],
	["weigh", ["weighted"]],
	["weird", ["weirdness"]],
	["well", ["wellness"]],
	["were", ["werewolf"]],
	["what", ["whatever"]],
	["whee", ["wheeeee", "wheeeeee"]],
	["wheee", ["wheeeeeee"]],
	["wheeee", ["wheeeeeeee"]],
	["when", ["whenever"]],
	["which", ["whichever"]],
	["whiz", ["whizzing"]],
	["who", ["whoaaa", "whoaaaa", "whoever", "whooop"]],
	["whole", ["wholesome"]],
	["wil", ["wilfully", "willed", "willies"]],
	["wild", ["wildlife"]],
	["will", ["willfully"]],
	["willing", ["willingness"]],
	["win", ["winding", "winged", "winking", "winslow"]],
	["wind", ["windshield"]],
	["wish", ["wishful"]],
	["with", ["without", "withstand"]],
	["won", ["wonder"]],
	["wonder", ["wonderful"]],
	["work", ["workers", "workshop"]],
	["worm", ["wormwood", "wormwoods"]],
	["worth", ["worthwhile"]],
	["wrap", ["wrapper"]],
	["wreck", ["wreckage"]],
	["year", ["yearbook"]],
	["your", ["yourself", "yourselves"]],
	["zip", ["zipper"]],
	["zok", ["zokbar"]],
]);
